version: '3'

services:
  fable-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/fable
    environment:
      - PYTHONPATH=/home/fable