version: '3.8'

services:
  fable-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/home/fable/logs
    environment:
      - PYTHONPATH=/home/fable
    command: python main.py

volumes:
  logs: