version: '3.8'

services:
  fable-api:
    build: .
    network_mode: "host"
    volumes:
      - ./logs:/home/fable/logs
      - ./secrets/service-account.json:/tmp/keys/service-account.json
    environment:
      - PYTHONPATH=/home/fable
      - MONGO_URL=mongodb://localhost:27017/fable
    command: python main.py

volumes:
  logs: